version: "3.9"

services:
    web:
        build: .
        container_name: django
        command: gunicorn finance_book.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - static_volume:/home/app/web/staticfiles
        expose:
            - 8000
        env_file:
            - ./.env.dev
        depends_on:
            - pgdb
    pgdb:
        image: postgres
        container_name: pgdb
        environment:
            - POSTGRES_DB=test
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - pgdata:/var/lib/postgresql/data/
    nginx:
        build: ./nginx
        volumes:
            - ./staticfiles:/home/app/web/staticfiles:ro
        ports:
            - 80:80
        depends_on:
            - web
volumes:
    pgdata:
    static_volume:
